#version: "3"
#
#services:
#  app:
#    image: my-app:latest
#    build: .
#    environment:
#      - DISPLAY=${DISPLAY}
#    volumes:
#      - /tmp/.X11-unix:/tmp/.X11-unix
#    network_mode: host


version: '3'
services:
    raylib:
        image: 'sahiljain11/smart-mirror'
        command: >
          ./jarvis.csj
        volumes:
            - .:/usr/src/smart-mirror/build
        working_dir: /usr/src/smart-mirror/build